//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grammars {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grammars.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;title&gt;[Name]&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body { font-family: Verdana; }
        ///
        ///        h1 {
        ///            background: gray;
        ///            margin: 0px;
        ///            padding: 3px;
        ///            width: 100%;
        ///        }
        ///
        ///        caption {
        ///            font-size: 14px;
        ///            font-weight: bolder;
        ///        }
        ///
        ///        #description {
        ///            border-bottom: 1px solid dimgray;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssignmentGrammarAnalysis {
            get {
                return ResourceManager.GetString("AssignmentGrammarAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;title&gt;[Name]&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body { font-family: Verdana; }
        ///
        ///        h1 {
        ///            background: gray;
        ///            margin: 0px;
        ///            padding: 3px;
        ///            width: 100%;
        ///        }
        ///
        ///        caption {
        ///            font-size: 14px;
        ///            font-weight: bolder;
        ///        }
        ///
        ///        #description {
        ///            border-bottom: 1px solid dimgray;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhonotacticsGrammarAnalysis {
            get {
                return ResourceManager.GetString("PhonotacticsGrammarAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .result {
        ///            margin: 0;
        ///            padding: 0;
        ///        }
        ///
        ///        .odd {
        ///        
        ///        
        ///
        ///        background: { OddColor }
        ///
        ///        ; 
        ///
        ///        }
        ///        .even {
        ///        
        ///        
        ///
        ///        background: { EvenColor }
        ///
        ///        ; 
        ///
        ///        border-top: 1px 
        ///
        ///        solid { DividerColor }
        ///
        ///        ; 
        ///
        ///        border-bottom: 1px 
        ///
        ///        solid { DividerColor }
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResultsTemplate {
            get {
                return ResourceManager.GetString("ResultsTemplate", resourceCulture);
            }
        }
    }
}
