'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TheRandomizerWPF.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.dwolla.com/hub/solitudesoftware.
        '''</summary>
        Friend ReadOnly Property Dwolla() As String
            Get
                Return ResourceManager.GetString("Dwolla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exception() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exception", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.reddit.com/r/TheRandomizer/wiki/grammars.
        '''</summary>
        Friend ReadOnly Property Grammars() As String
            Get
                Return ResourceManager.GetString("Grammars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to help\TheRandomizer.chm.
        '''</summary>
        Friend ReadOnly Property HelpFile() As String
            Get
                Return ResourceManager.GetString("HelpFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=RGRLDFD5WD2A2&amp;lc=US&amp;item_name=Solitude%20Software&amp;currency_code=USD&amp;bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted.
        '''</summary>
        Friend ReadOnly Property Paypal() As String
            Get
                Return ResourceManager.GetString("Paypal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''
        '''&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .result {
        '''            margin:0;
        '''            padding:0;
        '''        }
        '''        .odd {
        '''            background: {OddColor};
        '''        }
        '''        .even {
        '''            background: {EvenColor};
        '''            border-top: 1px solid {DividerColor};
        '''            border-bottom: 1px solid {DividerColor};
        '''        }
        '''        body {
        '''            font-famil [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ResultsTemplate() As String
            Get
                Return ResourceManager.GetString("ResultsTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;RollFunction&quot;
        '''        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        '''    &lt;Color name=&quot;Comment&quot; foreground=&quot;Green&quot; /&gt;
        '''    &lt;Color name=&quot;String&quot; foreground=&quot;Purple&quot; /&gt;
        '''    
        '''    &lt;!-- This is the main ruleset. --&gt;
        '''    &lt;RuleSet&gt;
        '''        &lt;Span color=&quot;Comment&quot; begin=&quot;#&quot; /&gt;
        '''        
        '''        &lt;Span color=&quot;String&quot;&gt;
        '''            &lt;Begin&gt;&apos;&lt;/Begin&gt;
        '''            &lt;End&gt;&apos;&lt;/End&gt;
        '''        &lt;/Span&gt;
        '''		
        '''		&lt;Span color=&quot;Orange&quot;&gt;
        '''			&lt;Begin&gt;[&lt;/Begin&gt;
        '''			&lt;End&gt;]&lt;/End&gt;
        '''		&lt;/Span&gt;
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RollFunction() As String
            Get
                Return ResourceManager.GetString("RollFunction", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
